version: '2'
services:
  web:
    build: .
    ports:
      - "8080:8080"
    links:
      - "mongo_db"
  mongo_db:
    image: mongo:4.0.9
    ports:
      - "27017:27017"
    volumes:
      - /opt/mongodb:/data/db